//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""dancing"",
            ""id"": ""dffe98ca-54b3-4aee-b7a9-69165fc6ed45"",
            ""actions"": [
                {
                    ""name"": ""FirstMove"",
                    ""type"": ""Button"",
                    ""id"": ""6e3ad4bb-a65b-4e94-921f-4237954bafb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondMove"",
                    ""type"": ""Button"",
                    ""id"": ""e3f29369-c264-487d-89fa-5c1fd93e973b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdMove"",
                    ""type"": ""Button"",
                    ""id"": ""8db7849b-47fd-4924-9aac-e180299dbe82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthMove"",
                    ""type"": ""Button"",
                    ""id"": ""a5bb4b5b-4840-487e-84ea-dcc0b0c4871b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d4b0adb5-36b5-41c9-a17c-333cf2d9d0e4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52074dc4-fd4a-48ac-98ab-a854954dbf22"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1638aeff-b54b-4df9-85da-3a4f9a9a672c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8585cbf-9626-4ff9-a973-897a570f8016"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b19fd2a3-f466-4538-a10f-395d43475755"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dcd8fd9-9f51-473d-b9e0-46edcafb764d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01823b55-ff81-46e6-bb84-ffd64b25bc7a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d9c261-3555-4d13-8467-6ed5d49a733b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // dancing
        m_dancing = asset.FindActionMap("dancing", throwIfNotFound: true);
        m_dancing_FirstMove = m_dancing.FindAction("FirstMove", throwIfNotFound: true);
        m_dancing_SecondMove = m_dancing.FindAction("SecondMove", throwIfNotFound: true);
        m_dancing_ThirdMove = m_dancing.FindAction("ThirdMove", throwIfNotFound: true);
        m_dancing_FourthMove = m_dancing.FindAction("FourthMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // dancing
    private readonly InputActionMap m_dancing;
    private IDancingActions m_DancingActionsCallbackInterface;
    private readonly InputAction m_dancing_FirstMove;
    private readonly InputAction m_dancing_SecondMove;
    private readonly InputAction m_dancing_ThirdMove;
    private readonly InputAction m_dancing_FourthMove;
    public struct DancingActions
    {
        private @PlayerActions m_Wrapper;
        public DancingActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstMove => m_Wrapper.m_dancing_FirstMove;
        public InputAction @SecondMove => m_Wrapper.m_dancing_SecondMove;
        public InputAction @ThirdMove => m_Wrapper.m_dancing_ThirdMove;
        public InputAction @FourthMove => m_Wrapper.m_dancing_FourthMove;
        public InputActionMap Get() { return m_Wrapper.m_dancing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DancingActions set) { return set.Get(); }
        public void SetCallbacks(IDancingActions instance)
        {
            if (m_Wrapper.m_DancingActionsCallbackInterface != null)
            {
                @FirstMove.started -= m_Wrapper.m_DancingActionsCallbackInterface.OnFirstMove;
                @FirstMove.performed -= m_Wrapper.m_DancingActionsCallbackInterface.OnFirstMove;
                @FirstMove.canceled -= m_Wrapper.m_DancingActionsCallbackInterface.OnFirstMove;
                @SecondMove.started -= m_Wrapper.m_DancingActionsCallbackInterface.OnSecondMove;
                @SecondMove.performed -= m_Wrapper.m_DancingActionsCallbackInterface.OnSecondMove;
                @SecondMove.canceled -= m_Wrapper.m_DancingActionsCallbackInterface.OnSecondMove;
                @ThirdMove.started -= m_Wrapper.m_DancingActionsCallbackInterface.OnThirdMove;
                @ThirdMove.performed -= m_Wrapper.m_DancingActionsCallbackInterface.OnThirdMove;
                @ThirdMove.canceled -= m_Wrapper.m_DancingActionsCallbackInterface.OnThirdMove;
                @FourthMove.started -= m_Wrapper.m_DancingActionsCallbackInterface.OnFourthMove;
                @FourthMove.performed -= m_Wrapper.m_DancingActionsCallbackInterface.OnFourthMove;
                @FourthMove.canceled -= m_Wrapper.m_DancingActionsCallbackInterface.OnFourthMove;
            }
            m_Wrapper.m_DancingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstMove.started += instance.OnFirstMove;
                @FirstMove.performed += instance.OnFirstMove;
                @FirstMove.canceled += instance.OnFirstMove;
                @SecondMove.started += instance.OnSecondMove;
                @SecondMove.performed += instance.OnSecondMove;
                @SecondMove.canceled += instance.OnSecondMove;
                @ThirdMove.started += instance.OnThirdMove;
                @ThirdMove.performed += instance.OnThirdMove;
                @ThirdMove.canceled += instance.OnThirdMove;
                @FourthMove.started += instance.OnFourthMove;
                @FourthMove.performed += instance.OnFourthMove;
                @FourthMove.canceled += instance.OnFourthMove;
            }
        }
    }
    public DancingActions @dancing => new DancingActions(this);
    public interface IDancingActions
    {
        void OnFirstMove(InputAction.CallbackContext context);
        void OnSecondMove(InputAction.CallbackContext context);
        void OnThirdMove(InputAction.CallbackContext context);
        void OnFourthMove(InputAction.CallbackContext context);
    }
}
